### ISSUE TITLE
[Feature Request] Add support for NRTM

### ISSUE THREAD

**Issue by gereons** [temetherian/epitome#2]
It would be great if TOs using NRTM could automatically create and update tournaments on epitome. To accomplish this, NRTM would first need to create a Tournament using a "new tournament" API endpoint that returns URIs for players and uploading, and later post its tournament data to that "uploading" endpoint.

Here's a real-world example of a JSON dump from a tournament including a top cut: https://www.dropbox.com/s/1y3k8d4ro68bp7p/NRTM.json?dl=0

The JSON format is described by this schema: http://steffens.org/nrtm/nrtm-schema.json

**Comment by temetherian** [comment]
I've added support for using NRTM JSON files (#3) and added some endpoints that give a more parsable response (#4).

I only tested the endpoints with curl, but it seems functional.
`curl http://localhost:8080/_api/create -d shortname=nrtm -d codeword=secret -d title='NRTM test' -d app=nrtm`
`curl http://localhost:8080/_api/update -d shortname=nrtm -d codeword=secret --data-urlencode export@NRTM.json`

I'm not really sure what differences an in-progress NRTM json file has, but I guessed that Swiss games would exist with all scores at 0, and that elimination games would have both winner fields as false. If so, the UI should handle those situations correctly, I think.

**Comment by gereons** [comment]
Fantastic, thank you! I'll go check those out later when I return from playing our monthly GNK :)

In-progress data exports do not contain any data about unplayed rounds, neither swiss nor elimination, since there really is no way for the app to know ahead of time what they'd look like, or even if they will exist at all.

**Comment by temetherian** [comment]
Yeah, my curiosity about unplayed rounds was actually more about the current round than about anything further. (If only it were possible to predict the future! :smile:) But if NRTM can/does include the pairings it's generated for the current round as these sorts of scoreless games, epiTOME can let players look them up.

**Comment by gereons** [comment]
Ah, understood ;)

You guessed correctly. Scores are 0:0, and eliminations have no winners.

Since I have no python experience whatsoever, and also no GCS account: is there any easy way for me to run this locally, or should I use the live server for my tests?

**Comment by temetherian** [comment]
You won't need a Google Cloud account to run it locally, but you would need to install Python and an [App Engine SDK](https://cloud.google.com/appengine/docs/standard/python/download). (Either the cloud SDK or the original App Engine SDK should work.)

`dev_appserver.py ./` in the epiTOME directory will start it on localhost:8080, with useful admin stuff at localhost:8000/datastore and localhost:8000/blobstore.

If that's not working, the live server should be able to handle a little testing.

**Comment by gereons** [comment]
Works great, thank you. I've got the low-level stuff pretty much sorted out, now I need to think about how this should work in the UI.

Is anr-epitome.appspot.com going to stay the official host?

**Comment by temetherian** [comment]
I don't have any plans to use a different domain right now. But in any case, anr-epitome.appspot.com would continue to work, so it would probably be the safest target for API calls.

**Comment by gereons** [comment]
FYI, I have just released an update of NRTM that has support for epiTOME. Hopefully this catches on!
